# Generated by Django 6.0.2 on 2026-03-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='الاسم الكامل')),
                ('slug', models.SlugField(help_text='سيتم إنشاؤه تلقائياً من الاسم الكامل', max_length=255, unique=True, verbose_name='الرابط المختصر')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='السيرة الذاتية')),
                ('profile_image', models.CharField(blank=True, db_column='profile_image', max_length=255, null=True, verbose_name='صورة الملف الشخصي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, unique=True, verbose_name='الاسم (عربي)')),
                ('name_ku', models.CharField(max_length=255, unique=True, verbose_name='الاسم (كردي)')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(help_text='سيتم إنشاؤه تلقائياً من الاسم الإنجليزي', max_length=255, unique=True, verbose_name='الرابط المختصر')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='تاريخ آخر تعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
            ],
        ),
    ]
