# Generated by Django 6.0.2 on 2026-04-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='الرابط المختصر')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='السيرة الذاتية')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='authors/%Y/%m/%d/', verbose_name='صورة الملف الشخصي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ku', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, unique=True, verbose_name='الاسم (عربي)')),
                ('name_ku', models.CharField(max_length=255, unique=True, verbose_name='الاسم (كردي)')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='الرابط المختصر')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='تاريخ آخر تعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='الرابط المختصر')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم (عربي)')),
                ('name_ku', models.CharField(max_length=255, verbose_name='الاسم (كردي)')),
                ('name_en', models.CharField(max_length=255, verbose_name='الاسم (إنجليزي)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contenttype')),
            ],
            options={
                'verbose_name': 'الوسوم',
                'verbose_name_plural': 'الوسوم',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ar', 'Ar'), ('ku', 'Ku'), ('en', 'En')], db_index=True, default='ar', help_text='لغة المحتوى', max_length=10, verbose_name='اللغة')),
                ('title', models.CharField(db_index=True, help_text='عنوان المقال حسب اللغة المختارة', max_length=500, verbose_name='العنوان')),
                ('excerpt', models.TextField(blank=True, help_text='ملخص قصير للمقال', null=True, verbose_name='الملخص')),
                ('content', models.TextField(blank=True, help_text='المحتوى الرئيسي للمقال', null=True, verbose_name='المحتوى')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان SEO مختلف عن العنوان الرئيسي', max_length=255, null=True, verbose_name='العنوان التعريفي')),
                ('meta_description', models.TextField(blank=True, help_text='وصف SEO لمحركات البحث', null=True, verbose_name='الوصف التعريفي')),
                ('featured_image', models.ImageField(blank=True, help_text='الصورة المميزة للمقال', null=True, upload_to='posts/%Y/%m/%d/', verbose_name='الصورة المميزة')),
                ('view_count', models.IntegerField(db_index=True, default=0, verbose_name='عدد المشاهدات')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ النشر')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.authors', verbose_name='الكاتب')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.categories', verbose_name='التصنيف')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.contenttype', verbose_name='نوع المحتوى')),
                ('original_post', models.ForeignKey(blank=True, help_text='المرجع للمقال الأصلي في حالة الترجمات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='content.posts', verbose_name='المقال الأصلي')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='content.tags', verbose_name='الوسوم')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'Pdf'), ('audio', 'Audio')], max_length=20, verbose_name='نوع الملف')),
                ('src', models.FileField(blank=True, null=True, upload_to='media_files/%Y/%m/%d/', verbose_name='الملف')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='رابط خارجي')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='النص البديل')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='الشرح')),
                ('mime_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع MIME')),
                ('file_size_kb', models.IntegerField(blank=True, null=True, verbose_name='حجم الملف (KB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='content.posts', verbose_name='المقال')),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'ملفات الوسائط',
                'db_table': 'content_media_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('dialogue_session', 'Dialogue Session'), ('forum', 'Forum'), ('meeting', 'Meeting'), ('center_news', 'Center News')], default='meeting', max_length=50, verbose_name='نوع الحدث')),
                ('event_date', models.DateTimeField(verbose_name='تاريخ الحدث')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('attendees_count', models.IntegerField(default=0, verbose_name='عدد الحضور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='content.posts')),
            ],
            options={
                'verbose_name': 'حدث',
                'verbose_name_plural': 'الأحداث',
                'db_table': 'content_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=True, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.posts')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'db_table': 'content_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('book', 'Book'), ('magazine', 'Magazine')], default='book', max_length=50, verbose_name='نوع النشر')),
                ('issue_number', models.CharField(max_length=50, verbose_name='رقم الإصدار')),
                ('volume', models.CharField(max_length=50, verbose_name='المجلد')),
                ('isbn', models.CharField(max_length=20, verbose_name='رقم ISBN')),
                ('download_url', models.URLField(blank=True, null=True, verbose_name='رابط التحميل')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/%Y/%m/%d/', verbose_name='صورة الغلاف')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('publish_year', models.IntegerField(blank=True, null=True, verbose_name='سنة النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='content.posts')),
            ],
            options={
                'verbose_name': 'نشر',
                'verbose_name_plural': 'النشرات',
                'db_table': 'content_publications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='السؤال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='content.posts')),
            ],
            options={
                'verbose_name': 'استبيان',
                'verbose_name_plural': 'الاستبيانات',
                'db_table': 'content_surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='نص الخيار')),
                ('vote_count', models.IntegerField(default=0, verbose_name='عدد الأصوات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.surveys')),
            ],
            options={
                'verbose_name': 'خيار استبيان',
                'verbose_name_plural': 'خيارات الاستبيان',
                'db_table': 'content_survey_options',
                'ordering': ['-created_at'],
            },
        ),
    ]
