# Generated by Django 6.0.2 on 2026-03-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='الرابط المختصر'),
        ),
    ]
