# Generated by Django 6.0.2 on 2026-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_authors_profile_image_alter_authors_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='الرابط المختصر'),
        ),
    ]
