# Generated by Django 6.0.2 on 2026-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_authors_full_name_alter_authors_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/%Y/%m/%d/', verbose_name='صورة الملف الشخصي'),
        ),
    ]
