# Generated by Django 6.0.2 on 2026-03-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_authors_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='الرابط المختصر')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم (عربي)')),
                ('name_ku', models.CharField(max_length=255, verbose_name='الاسم (كردي)')),
                ('name_en', models.CharField(max_length=255, verbose_name='الاسم (إنجليزي)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
            ],
        ),
    ]
