# Generated by Django 6.0.2 on 2026-03-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='sort_order',
        ),
    ]
