# Generated by Django 6.0.2 on 2026-03-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_categories_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('ku', 'كردي'), ('en', 'English')], db_index=True, default='ar', help_text='لغة المحتوى', max_length=10, verbose_name='اللغة')),
                ('slug', models.SlugField(help_text='رابط URL للمقال', max_length=500, verbose_name='الرابط المختصر')),
                ('title', models.CharField(db_index=True, help_text='عنوان المقال حسب اللغة المختارة', max_length=500, verbose_name='العنوان')),
                ('excerpt', models.TextField(blank=True, help_text='ملخص قصير للمقال', null=True, verbose_name='الملخص')),
                ('content', models.TextField(help_text='المحتوى الرئيسي للمقال', verbose_name='المحتوى')),
                ('content_type', models.CharField(choices=[('text', 'نص'), ('infographic', 'إنفوجرافيك'), ('video', 'فيديو'), ('documentary', 'وثائقي'), ('report', 'تقرير'), ('survey', 'استبيان'), ('publication', 'منشور'), ('event', 'فعالية')], db_index=True, default='text', max_length=20, verbose_name='نوع المحتوى')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان SEO مختلف عن العنوان الرئيسي', max_length=255, null=True, verbose_name='العنوان التعريفي')),
                ('meta_description', models.TextField(blank=True, help_text='وصف SEO لمحركات البحث', null=True, verbose_name='الوصف التعريفي')),
                ('featured_image', models.CharField(blank=True, help_text='رابط الصورة المميزة للمقال', max_length=500, null=True, verbose_name='الصورة المميزة')),
                ('view_count', models.IntegerField(db_index=True, default=0, verbose_name='عدد المشاهدات')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ النشر')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('author', models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.authors', verbose_name='الكاتب')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.categories', verbose_name='التصنيف')),
                ('original_post', models.ForeignKey(blank=True, help_text='المرجع للمقال الأصلي في حالة الترجمات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='content.posts', verbose_name='المقال الأصلي')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='content.tags', verbose_name='الوسوم')),
            ],
        ),
    ]
