# Generated by Django 6.0.2 on 2026-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(help_text='رابط URL للمقال', max_length=500, unique=True, verbose_name='الرابط المختصر'),
        ),
    ]
