# Generated by Django 6.0.2 on 2026-03-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_posts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
