# Generated by Django 6.0.2 on 2026-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='الصورة المميزة للمقال', null=True, upload_to='posts/%Y/%m/%d/', verbose_name='الصورة المميزة'),
        ),
    ]
