# Generated by Django 6.0.2 on 2026-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_posts_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('infographic', 'Infographic'), ('video', 'Video'), ('documentary', 'Documentary'), ('report', 'Report'), ('survey', 'Survey'), ('publication', 'Publication'), ('event', 'Event')], db_index=True, default='text', max_length=20, verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='language',
            field=models.CharField(choices=[('ar', 'Ar'), ('ku', 'Ku'), ('en', 'En')], db_index=True, default='ar', help_text='لغة المحتوى', max_length=10, verbose_name='اللغة'),
        ),
    ]
