# Generated by Django 6.0.2 on 2026-03-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_categories_options_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='السؤال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='content.posts')),
            ],
            options={
                'verbose_name': 'استبيان',
                'verbose_name_plural': 'الاستبيانات',
                'db_table': 'content_surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='نص الخيار')),
                ('vote_count', models.IntegerField(default=0, verbose_name='عدد الأصوات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.surveys')),
            ],
            options={
                'verbose_name': 'خيار استبيان',
                'verbose_name_plural': 'خيارات الاستبيان',
                'db_table': 'content_survey_options',
                'ordering': ['-created_at'],
            },
        ),
    ]
