# Generated by Django 6.0.2 on 2026-03-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_surveys_surveyoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='نوع الحدث')),
                ('event_date', models.DateTimeField(verbose_name='تاريخ الحدث')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('attendees_count', models.IntegerField(default=0, verbose_name='عدد الحضور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='content.posts')),
            ],
            options={
                'verbose_name': 'حدث',
                'verbose_name_plural': 'الأحداث',
                'db_table': 'content_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
