# Generated by Django 6.0.2 on 2026-03-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(max_length=50, verbose_name='نوع النشر')),
                ('issue_number', models.CharField(max_length=50, verbose_name='رقم الإصدار')),
                ('volume', models.CharField(max_length=50, verbose_name='المجلد')),
                ('isbn', models.CharField(max_length=20, verbose_name='رقم ISBN')),
                ('download_url', models.URLField(blank=True, null=True, verbose_name='رابط التحميل')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/%Y/%m/%d/', verbose_name='صورة الغلاف')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('publish_year', models.IntegerField(blank=True, null=True, verbose_name='سنة النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='content.posts')),
            ],
            options={
                'verbose_name': 'نشر',
                'verbose_name_plural': 'النشرات',
                'db_table': 'content_publications',
                'ordering': ['-created_at'],
            },
        ),
    ]
