# Generated by Django 6.0.2 on 2026-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('dialogue_session', 'Dialogue Session'), ('forum', 'Forum'), ('meeting', 'Meeting'), ('center_news', 'Center News')], default='meeting', max_length=50, verbose_name='نوع الحدث'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='publication_type',
            field=models.CharField(choices=[('book', 'Book'), ('magazine', 'Magazine')], default='book', max_length=50, verbose_name='نوع النشر'),
        ),
    ]
