# Generated by Django 6.0.2 on 2026-03-31 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_events_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'Pdf'), ('audio', 'Audio')], max_length=20, verbose_name='نوع الملف')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='media_files/images/%Y/%m/%d/', verbose_name='ملف الصورة')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط الفيديو')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media_files/audio/%Y/%m/%d/', verbose_name='ملف الصوت')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='media_files/docs/%Y/%m/%d/', verbose_name='ملف PDF أو مستند')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='النص البديل')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='الشرح')),
                ('mime_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع MIME')),
                ('file_size_kb', models.IntegerField(blank=True, null=True, verbose_name='حجم الملف (KB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='content.posts')),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'ملفات الوسائط',
                'db_table': 'content_media_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
