# Generated by Django 6.0.2 on 2026-04-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_mediafiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='موافق عليه'),
        ),
    ]
