# Generated by Django 6.0.2 on 2026-04-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_comments_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.authors', verbose_name='الكاتب'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='الرابط المختصر'),
        ),
    ]
