# Generated by Django 6.0.2 on 2026-04-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_authors_slug_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafiles',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='mediafiles',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='mediafiles',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='mediafiles',
            name='video_url',
        ),
        migrations.AddField(
            model_name='mediafiles',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='media_files/%Y/%m/%d/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='mediafiles',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='content.posts', verbose_name='المقال'),
        ),
    ]
