# Generated by Django 6.0.2 on 2026-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_mediafiles_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafiles',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط خارجي'),
        ),
    ]
