# Generated by Django 6.0.2 on 2026-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_mediafiles_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, help_text='المحتوى الرئيسي للمقال', null=True, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content_type',
            field=models.CharField(choices=[('infographic', 'Infographic'), ('video', 'Video'), ('documentary', 'Documentary'), ('report', 'Report'), ('survey', 'Survey'), ('event', 'Event'), ('magazine', 'Magazine'), ('book', 'Book'), ('studies', 'Studies'), ('analytics', 'Analytics'), ('opinion_article', 'Opinion Article'), ('files', 'Files')], db_index=True, default='infographic', max_length=20, verbose_name='نوع المحتوى'),
        ),
    ]
